package com._labor.fakecord.domain.enums;

public enum NotificationType {
  MESSAGE_CREATE("MESSAGE_CREATE"),
  MESSAGE_UPDATE("MESSAGE_UPDATE"),
  MESSAGE_DELETE("MESSAGE_DELETE"),
  TYPING_START("TYPING_START"),

  DM_CREATE("DM_CREATE"),       
  GROUP_CREATE("GROUP_CREATE"),
  MEMBER_JOIN("MEMBER_JOIN"),
  MEMBER_LEAVE("MEMBER_LEAVE"),

  FRIEND_REQUEST_SENT("FRIEND_REQUEST_SENT"),
  FRIEND_REQUEST_ACCEPTED("FRIEND_REQUEST_ACCEPTED"),
  FRIEND_REMOVED("FRIEND_REMOVED"),

  NOTIFICATION_COUNT_UPDATE("NOTIFICATION_COUNT_UPDATE"),
  CHANNEL_READ_SYNC("CHANNEL_READ_SYNC");

  private final String value;

  NotificationType(String value) { this.value = value; }
}